export const GENRE_LIST = [
  'Ação',
  'Animação',
  'Antologia',
  'Aventura',
  'Biográfico',
  'Comédia',
  'Crime',
  'Drama',
  'Fantasia',
  'Ficção Científica',
  'Guerra',
  'História',
  'Humor',
  'Humor negro',
  'Isekai',
  'Jogo',
  'Mistério',
  'Musical',
  'Policial',
  'Psicológico',
  'Romance',
  'Sátira',
  'Sci-fi',
  'Slice of Life',
  'Sobrenatural',
  'Suspense',
  'Terror',
  'Thriller',
  'Thriller psicológico'
];